server:
  port: 8080
  servlet:
    context-path: /ContactApp
spring:
  datasource:
    initialization-mode: always
    password: mindpath
    url: jdbc:mysql://localhost:3306/restapi?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
